/* add your functions here */

function printHeader(){
    document.write("<header id=\"default\">")
	document.write("<table>")
    document.write("<tr>")
    document.write("<td><h1>David Reese</h1></td>")
	document.write("</tr>")
	document.write("<tr>")
    document.write("<td>")
	document.write("<a href=\"mailto:david33reese@gmail.com\"><button class=\"socials\"><img src=\"email.png\" width=\"30px\"></button></a>")
	document.write("<button onclick=location.assign(\"https://www.linkedin.com/in/davidreese3/\") class=\"socials\"><img src=\"linkedin.png\" width=\"30px\"></button>")
	document.write("<button onclick=location.assign(\"https://github.com/davidreese3\") class=\"socials\"><img src=\"github.png\" width=\"30px\"></button>")
	document.write("</td>")
	document.write("</tr>")
	document.write("</table>")
	document.write("<br>")
	document.write("<div id=\"profile\"><img src=\"Headshot.jpg\" width=\"100px\"></div>")
	document.write("<nav id=\"mainNav\">")
	document.write("<button onclick=location.assign(\"DR_Home.html\") class=\"mainNavButton\">Home</button>")
	document.write("<button onclick=location.assign(\"DR_Resume.html\") class=\"mainNavButton\">Resume</button>")
	document.write("<div class=\"dropdown\">")
	document.write("<button onclick=location.assign(\"DR_Projects.html\") id=\"project\">Projects</button>")
	document.write("<div class=\"dd-content\">")
	document.write("<a>Webpage Resume</a>")
	document.write("<a>Group Chat</a>")
	document.write("<a>JDBC Application</a>")
	document.write("<a>Hack Assembler</a>")
	document.write("<a>Job Scheduler</a>")
	document.write("</div>")
	document.write("</div>")
	document.write("<button onclick=location.assign(\"DR_Academic.html\") class=\"mainNavButton\">Academic History</button>")
	document.write("<button onclick=location.assign(\"DR_Contact.html\") class=\"mainNavButton\">Contact Me</button>")
	document.write("</nav>")
	document.write("</header>")
}